### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by axic** [wasmx/wasm-chisel#28]
From the README:

The configuration file starts with a ruleset entry, where the name can be anything. Inside the ruleset are its options.

```yaml
ewasm:
  - file: "target/wasm32-unknown-unknown/release/sentinel.wasm"
  - remapimports:
    - style: ewasm
  - deployer
```

**Comment by jakelang** [comment]
My proposed format:
```yaml
ruleset:
    - file: "file.wasm"
    - module:
        - name: "remapimports"
        - preset: "ewasm"
    - module:
        - name: "deployer"
```

**Comment by axic** [comment]
```
runevm:
  - input: "target/wasm32-unknown-unknown/release/runevm.wasm"
  - remapimports:
    - preset: ewasm
  - deployer
```

```
sha256:
  - input: "target/wasm32-unknown-unknown/release/ewasm_precompile_sha256.wasm"
  - output: "sha256.wasm"
  - remapimports:
    - preset: ewasm
```

**Comment by jakelang** [comment]
My proposed format:
```yaml
ruleset:
    - file: "file.wasm"
    - module:
        - name: "remapimports"
        - preset: "ewasm"
    - module:
        - name: "deployer"
```
