### ISSUE TITLE
YAML need to support multiple top level keys

### ISSUE THREAD

**Issue by axic** [wasmx/wasm-chisel#65]
This doesn't seem to work (e.g. only one of them is run, not sure which):
```
blake2:
  file: "target/wasm32-unknown-unknown/release/ewasm_precompile_blake2.wasm"
  remapimports:
    preset: "ewasm"
  trimexports:
    preset: "ewasm"

bls12pairing:
  file: "target/wasm32-unknown-unknown/release/ewasm_precompile_bls12pairing.wasm"
  remapimports:
    preset: "ewasm"
  trimexports:
    preset: "ewasm"
```
